# Generated by Django 5.0.1 on 2024-01-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_car_image_car_placa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
