# Generated by Django 5.0.1 on 2024-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_alter_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="plate",
        ),
        migrations.AddField(
            model_name="car",
            name="placa",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
