# Generated by Django 5.0.1 on 2024-01-23 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_remove_car_plate_car_placa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="placa",
            new_name="plate",
        ),
    ]
